[NCLSUP-714] Default to ASC ordering, when direction is null
project-ncl/bifrost pull request #385
Opened 2024-01-03 15:32 UTC by janinko

2024-01-03 16:54 UTC, michalovjan requested changes
+1 just fix Jenkins

2024-01-03 21:34 UTC, thescouser89 commented
Fixing it in #387

2024-01-03 21:37 UTC, thescouser89 commented
retest this please

2024-01-04 11:02 UTC, michalovjan approved these changes

2024-01-04 15:30 UTC, merged